//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClashN.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClashN.Resx.ResUI", typeof(ResUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All servers.
        /// </summary>
        public static string AllGroupProfiles {
            get {
                return ResourceManager.GetString("AllGroupProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export configuration file to clipboard successfully.
        /// </summary>
        public static string BatchExportSuccessfully {
            get {
                return ResourceManager.GetString("BatchExportSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the configuration file settings first.
        /// </summary>
        public static string CheckProfileSettings {
            get {
                return ResourceManager.GetString("CheckProfileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  configuration format is incorrect.
        /// </summary>
        public static string ConfigurationFormatIncorrect {
            get {
                return ResourceManager.GetString("ConfigurationFormatIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note that custom configuration relies entirely on your own configuration and does not work with all settings. If you want to use the system proxy, please modify the listening port manually..
        /// </summary>
        public static string CustomProfileTips {
            get {
                return ResourceManager.GetString("CustomProfileTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWN.
        /// </summary>
        public static string downloadSpeed {
            get {
                return ResourceManager.GetString("downloadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to download? {0}.
        /// </summary>
        public static string DownloadYesNo {
            get {
                return ResourceManager.GetString("DownloadYesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to enable Tun mode, please run as administrator.
        /// </summary>
        public static string EnableTunModeFailed {
            get {
                return ResourceManager.GetString("EnableTunModeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert configuration file.
        /// </summary>
        public static string FailedConversionConfiguration {
            get {
                return ResourceManager.GetString("FailedConversionConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate default configuration file.
        /// </summary>
        public static string FailedGenDefaultConfiguration {
            get {
                return ResourceManager.GetString("FailedGenDefaultConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Failed to get the default configuration.
        /// </summary>
        public static string FailedGetDefaultConfiguration {
            get {
                return ResourceManager.GetString("FailedGetDefaultConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import configuration file.
        /// </summary>
        public static string FailedImportedCustomProfile {
            get {
                return ResourceManager.GetString("FailedImportedCustomProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read configuration file.
        /// </summary>
        public static string FailedReadConfiguration {
            get {
                return ResourceManager.GetString("FailedReadConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please browse to import configuration file configuration.
        /// </summary>
        public static string FillProfileAddressCustom {
            get {
                return ResourceManager.GetString("FillProfileAddressCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is not the correct client configuration file, please check.
        /// </summary>
        public static string IncorrectClientConfiguration {
            get {
                return ResourceManager.GetString("IncorrectClientConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is not the correct configuration, please check.
        /// </summary>
        public static string Incorrectconfiguration {
            get {
                return ResourceManager.GetString("Incorrectconfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is not the correct configuration file configuration file, please check.
        /// </summary>
        public static string IncorrectProfileConfiguration {
            get {
                return ResourceManager.GetString("IncorrectProfileConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Configuration.
        /// </summary>
        public static string InitialConfiguration {
            get {
                return ResourceManager.GetString("InitialConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already up to date..
        /// </summary>
        public static string IsLatestCore {
            get {
                return ResourceManager.GetString("IsLatestCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already up to date..
        /// </summary>
        public static string IsLatestN {
            get {
                return ResourceManager.GetString("IsLatestN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add configuration file.
        /// </summary>
        public static string menuAddProfile {
            get {
                return ResourceManager.GetString("menuAddProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add configuration file from clipboard (Ctrl+V).
        /// </summary>
        public static string menuAddProfileViaClipboard {
            get {
                return ResourceManager.GetString("menuAddProfileViaClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR code on the screen.
        /// </summary>
        public static string menuAddProfileViaScan {
            get {
                return ResourceManager.GetString("menuAddProfileViaScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all service statistics.
        /// </summary>
        public static string menuClearStatistic {
            get {
                return ResourceManager.GetString("menuClearStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone selected configuration file.
        /// </summary>
        public static string menuCloneProfile {
            get {
                return ResourceManager.GetString("menuCloneProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Connection.
        /// </summary>
        public static string menuConnectionClose {
            get {
                return ResourceManager.GetString("menuConnectionClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All Connection.
        /// </summary>
        public static string menuConnectionCloseAll {
            get {
                return ResourceManager.GetString("menuConnectionCloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Local File.
        /// </summary>
        public static string menuEditLocalFile {
            get {
                return ResourceManager.GetString("menuEditLocalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit configuration file.
        /// </summary>
        public static string menuEditProfile {
            get {
                return ResourceManager.GetString("menuEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string menuExit {
            get {
                return ResourceManager.GetString("menuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export configuration file to clipboard (Ctrl+C).
        /// </summary>
        public static string menuExportProfile {
            get {
                return ResourceManager.GetString("menuExportProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct.
        /// </summary>
        public static string menuModeDirect {
            get {
                return ResourceManager.GetString("menuModeDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        public static string menuModeGlobal {
            get {
                return ResourceManager.GetString("menuModeGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not change.
        /// </summary>
        public static string menuModeNothing {
            get {
                return ResourceManager.GetString("menuModeNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule.
        /// </summary>
        public static string menuModeRule {
            get {
                return ResourceManager.GetString("menuModeRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string menuProfile {
            get {
                return ResourceManager.GetString("menuProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Qrcode.
        /// </summary>
        public static string menuProfileQrcode {
            get {
                return ResourceManager.GetString("menuProfileQrcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Profile (F5).
        /// </summary>
        public static string menuProfileReload {
            get {
                return ResourceManager.GetString("menuProfileReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Node Latency Test.
        /// </summary>
        public static string menuProxiesDelaytest {
            get {
                return ResourceManager.GetString("menuProxiesDelaytest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Node Latency Test.
        /// </summary>
        public static string menuProxiesDelaytestPart {
            get {
                return ResourceManager.GetString("menuProxiesDelaytestPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Proxies (F5).
        /// </summary>
        public static string menuProxiesReload {
            get {
                return ResourceManager.GetString("menuProxiesReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select active node (Enter).
        /// </summary>
        public static string menuProxiesSelectActivity {
            get {
                return ResourceManager.GetString("menuProxiesSelectActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected configuration files (Delete).
        /// </summary>
        public static string menuRemoveProfile {
            get {
                return ResourceManager.GetString("menuRemoveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule mode.
        /// </summary>
        public static string menuRulemode {
            get {
                return ResourceManager.GetString("menuRulemode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as active configuration file (Enter).
        /// </summary>
        public static string menuSetDefaultProfile {
            get {
                return ResourceManager.GetString("menuSetDefaultProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update subscription without proxy.
        /// </summary>
        public static string menuSubUpdate {
            get {
                return ResourceManager.GetString("menuSubUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update selected subscription without proxy.
        /// </summary>
        public static string menuSubUpdateSelected {
            get {
                return ResourceManager.GetString("menuSubUpdateSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update selected subscription with proxy.
        /// </summary>
        public static string menuSubUpdateSelectedViaProxy {
            get {
                return ResourceManager.GetString("menuSubUpdateSelectedViaProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update subscription with proxy.
        /// </summary>
        public static string menuSubUpdateViaProxy {
            get {
                return ResourceManager.GetString("menuSubUpdateViaProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System proxy.
        /// </summary>
        public static string menuSystemproxy {
            get {
                return ResourceManager.GetString("menuSystemproxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear system proxy.
        /// </summary>
        public static string menuSystemProxyClear {
            get {
                return ResourceManager.GetString("menuSystemProxyClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not change system proxy.
        /// </summary>
        public static string menuSystemProxyNothing {
            get {
                return ResourceManager.GetString("menuSystemProxyNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pac Mode.
        /// </summary>
        public static string menuSystemProxyPac {
            get {
                return ResourceManager.GetString("menuSystemProxyPac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set system proxy.
        /// </summary>
        public static string menuSystemProxySet {
            get {
                return ResourceManager.GetString("menuSystemProxySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear original subscription content.
        /// </summary>
        public static string MsgClearSubscription {
            get {
                return ResourceManager.GetString("MsgClearSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Core successfully.
        /// </summary>
        public static string MsgDownloadCoreSuccessfully {
            get {
                return ResourceManager.GetString("MsgDownloadCoreSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download GeoFile: {0} successfully.
        /// </summary>
        public static string MsgDownloadGeoFileSuccessfully {
            get {
                return ResourceManager.GetString("MsgDownloadGeoFileSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import subscription content.
        /// </summary>
        public static string MsgFailedImportSubscription {
            get {
                return ResourceManager.GetString("MsgFailedImportSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the subscription content successfully.
        /// </summary>
        public static string MsgGetSubscriptionSuccessfully {
            get {
                return ResourceManager.GetString("MsgGetSubscriptionSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations (Filter : {0}).
        /// </summary>
        public static string MsgInformationTitle {
            get {
                return ResourceManager.GetString("MsgInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the address (Url).
        /// </summary>
        public static string MsgNeedUrl {
            get {
                return ResourceManager.GetString("MsgNeedUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid subscriptions set.
        /// </summary>
        public static string MsgNoValidSubscription {
            get {
                return ResourceManager.GetString("MsgNoValidSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve {0} successfully.
        /// </summary>
        public static string MsgParsingSuccessfully {
            get {
                return ResourceManager.GetString("MsgParsingSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip this subscription update.
        /// </summary>
        public static string MsgSkipSubscriptionUpdate {
            get {
                return ResourceManager.GetString("MsgSkipSubscriptionUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start getting subscriptions.
        /// </summary>
        public static string MsgStartGettingSubscriptions {
            get {
                return ResourceManager.GetString("MsgStartGettingSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start updating {0}....
        /// </summary>
        public static string MsgStartUpdating {
            get {
                return ResourceManager.GetString("MsgStartUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid subscription content.
        /// </summary>
        public static string MsgSubscriptionDecodingFailed {
            get {
                return ResourceManager.GetString("MsgSubscriptionDecodingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to continue?.
        /// </summary>
        public static string MsgSureContinue {
            get {
                return ResourceManager.GetString("MsgSureContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is unpacking....
        /// </summary>
        public static string MsgUnpacking {
            get {
                return ResourceManager.GetString("MsgUnpacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Core failed, see the log for details.
        /// </summary>
        public static string MsgUpdateCoreCoreFailed {
            get {
                return ResourceManager.GetString("MsgUpdateCoreCoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Core successfully.
        /// </summary>
        public static string MsgUpdateCoreCoreSuccessfully {
            get {
                return ResourceManager.GetString("MsgUpdateCoreCoreSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Core successfully! Restarting service....
        /// </summary>
        public static string MsgUpdateCoreCoreSuccessfullyMore {
            get {
                return ResourceManager.GetString("MsgUpdateCoreCoreSuccessfullyMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update subscription end.
        /// </summary>
        public static string MsgUpdateSubscriptionEnd {
            get {
                return ResourceManager.GetString("MsgUpdateSubscriptionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update subscription starts.
        /// </summary>
        public static string MsgUpdateSubscriptionStart {
            get {
                return ResourceManager.GetString("MsgUpdateSubscriptionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  This feature relies on the Http global proxy, please set it correctly first..
        /// </summary>
        public static string NeedHttpGlobalProxy {
            get {
                return ResourceManager.GetString("NeedHttpGlobalProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core not found, please download: {0}.
        /// </summary>
        public static string NotFoundCore {
            get {
                return ResourceManager.GetString("NotFoundCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Run As Admin.
        /// </summary>
        public static string NotRunAsAdmin {
            get {
                return ResourceManager.GetString("NotRunAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan completed, no valid QR code found.
        /// </summary>
        public static string NoValidQRcodeFound {
            get {
                return ResourceManager.GetString("NoValidQRcodeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  operation failed, please check retry.
        /// </summary>
        public static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation success.
        /// </summary>
        public static string OperationSuccess {
            get {
                return ResourceManager.GetString("OperationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Fill Remarks.
        /// </summary>
        public static string PleaseFillRemarks {
            get {
                return ResourceManager.GetString("PleaseFillRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the encryption method.
        /// </summary>
        public static string PleaseSelectEncryption {
            get {
                return ResourceManager.GetString("PleaseSelectEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the configuration file first.
        /// </summary>
        public static string PleaseSelectProfile {
            get {
                return ResourceManager.GetString("PleaseSelectProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an agreement.
        /// </summary>
        public static string PleaseSelectProtocol {
            get {
                return ResourceManager.GetString("PleaseSelectProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select rules.
        /// </summary>
        public static string PleaseSelectRules {
            get {
                return ResourceManager.GetString("PleaseSelectRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global hotkey {0} registered failed, reason {1}.
        /// </summary>
        public static string RegisterGlobalHotkeyFailed {
            get {
                return ResourceManager.GetString("RegisterGlobalHotkeyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global hotkey {0} registered successfully.
        /// </summary>
        public static string RegisterGlobalHotkeySuccessfully {
            get {
                return ResourceManager.GetString("RegisterGlobalHotkeySuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove the configuration file?.
        /// </summary>
        public static string RemoveProfile {
            get {
                return ResourceManager.GetString("RemoveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run As Admin.
        /// </summary>
        public static string RunAsAdmin {
            get {
                return ResourceManager.GetString("RunAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: After this function relies on the Http global proxy test, please manually adjust the Http global proxy and active node!.
        /// </summary>
        public static string SpeedProfileTips {
            get {
                return ResourceManager.GetString("SpeedProfileTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start service ({0})....
        /// </summary>
        public static string StartService {
            get {
                return ResourceManager.GetString("StartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful configuration
        ///{0}.
        /// </summary>
        public static string SuccessfulConfiguration {
            get {
                return ResourceManager.GetString("SuccessfulConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully imported configuration file.
        /// </summary>
        public static string SuccessfullyImportedCustomProfile {
            get {
                return ResourceManager.GetString("SuccessfullyImportedCustomProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import configuration file from clipboard successfully..
        /// </summary>
        public static string SuccessfullyImportedProfileViaClipboard {
            get {
                return ResourceManager.GetString("SuccessfullyImportedProfileViaClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan import successfully.
        /// </summary>
        public static string SuccessfullyImportedProfileViaScan {
            get {
                return ResourceManager.GetString("SuccessfullyImportedProfileViaScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from clipboard.
        /// </summary>
        public static string TbAddProfileViaClipboard {
            get {
                return ResourceManager.GetString("TbAddProfileViaClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string TbAddress {
            get {
                return ResourceManager.GetString("TbAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local file.
        /// </summary>
        public static string TbAddressAs {
            get {
                return ResourceManager.GetString("TbAddressAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string TbAlias {
            get {
                return ResourceManager.GetString("TbAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoRefresh.
        /// </summary>
        public static string TbAutoRefresh {
            get {
                return ResourceManager.GetString("TbAutoRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string TbBrowse {
            get {
                return ResourceManager.GetString("TbBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TbCancel {
            get {
                return ResourceManager.GetString("TbCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear system proxy.
        /// </summary>
        public static string TbClearSystemProxy {
            get {
                return ResourceManager.GetString("TbClearSystemProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string TbConfirm {
            get {
                return ResourceManager.GetString("TbConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string TbConnections {
            get {
                return ResourceManager.GetString("TbConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core type.
        /// </summary>
        public static string TbCoreType {
            get {
                return ResourceManager.GetString("TbCoreType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display GUI.
        /// </summary>
        public static string TbDisplayGUI {
            get {
                return ResourceManager.GetString("TbDisplayGUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string TbEdit {
            get {
                return ResourceManager.GetString("TbEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable subscription conversion.
        /// </summary>
        public static string TbEnableConvert {
            get {
                return ResourceManager.GetString("TbEnableConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tun.
        /// </summary>
        public static string TbEnableTun {
            get {
                return ResourceManager.GetString("TbEnableTun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Tun mode.
        /// </summary>
        public static string TbEnableTunAs {
            get {
                return ResourceManager.GetString("TbEnableTunAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string TbEnableUpdate {
            get {
                return ResourceManager.GetString("TbEnableUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Update subscription.
        /// </summary>
        public static string TbEnableUpdateAs {
            get {
                return ResourceManager.GetString("TbEnableUpdateAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string TbFilter {
            get {
                return ResourceManager.GetString("TbFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlobalHotkey Setting.
        /// </summary>
        public static string TbGlobalHotkeySetting {
            get {
                return ResourceManager.GetString("TbGlobalHotkeySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set directly by pressing the keyboard, Take effect after restart.
        /// </summary>
        public static string TbGlobalHotkeySettingTip {
            get {
                return ResourceManager.GetString("TbGlobalHotkeySettingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string TbHelp {
            get {
                return ResourceManager.GetString("TbHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string TbHelpCheck {
            get {
                return ResourceManager.GetString("TbHelpCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clashN Project.
        /// </summary>
        public static string TbHelpProject {
            get {
                return ResourceManager.GetString("TbHelpProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to.
        /// </summary>
        public static string TbHelpProjectGo {
            get {
                return ResourceManager.GetString("TbHelpProjectGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Line.
        /// </summary>
        public static string TbLineCount {
            get {
                return ResourceManager.GetString("TbLineCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string TbLogs {
            get {
                return ResourceManager.GetString("TbLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations.
        /// </summary>
        public static string TbMsgTitle {
            get {
                return ResourceManager.GetString("TbMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not change system proxy.
        /// </summary>
        public static string TbNotChangeSystemProxy {
            get {
                return ResourceManager.GetString("TbNotChangeSystemProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string TbProfiles {
            get {
                return ResourceManager.GetString("TbProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion.
        /// </summary>
        public static string TbPromotion {
            get {
                return ResourceManager.GetString("TbPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the button below to support the developer..
        /// </summary>
        public static string TbPromotionInformation {
            get {
                return ResourceManager.GetString("TbPromotionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxies.
        /// </summary>
        public static string TbProxies {
            get {
                return ResourceManager.GetString("TbProxies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Core.
        /// </summary>
        public static string TbReloadCore {
            get {
                return ResourceManager.GetString("TbReloadCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string TbReset {
            get {
                return ResourceManager.GetString("TbReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string TbSave {
            get {
                return ResourceManager.GetString("TbSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as active.
        /// </summary>
        public static string TbSetDefaultProfile {
            get {
                return ResourceManager.GetString("TbSetDefaultProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set system proxy.
        /// </summary>
        public static string TbSetSystemProxy {
            get {
                return ResourceManager.GetString("TbSetSystemProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TbSettings {
            get {
                return ResourceManager.GetString("TbSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced proxy settings, protocol selection (optional).
        /// </summary>
        public static string TbSettingsAdvancedProtocol {
            get {
                return ResourceManager.GetString("TbSettingsAdvancedProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow connections from the LAN.
        /// </summary>
        public static string TbSettingsAllowLAN {
            get {
                return ResourceManager.GetString("TbSettingsAllowLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Port.
        /// </summary>
        public static string TbSettingsAPIPort {
            get {
                return ResourceManager.GetString("TbSettingsAPIPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto hide startup.
        /// </summary>
        public static string TbSettingsAutoHideStartup {
            get {
                return ResourceManager.GetString("TbSettingsAutoHideStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic latency test interval (minutes).
        /// </summary>
        public static string TbSettingsAutoTest {
            get {
                return ResourceManager.GetString("TbSettingsAutoTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic update interval of subscriptions (hours).
        /// </summary>
        public static string TbSettingsAutoUpdate {
            get {
                return ResourceManager.GetString("TbSettingsAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClashN settings.
        /// </summary>
        public static string TbSettingsClashN {
            get {
                return ResourceManager.GetString("TbSettingsClashN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        public static string TbSettingsColorMode {
            get {
                return ResourceManager.GetString("TbSettingsColorMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core settings.
        /// </summary>
        public static string TbSettingsCore {
            get {
                return ResourceManager.GetString("TbSettingsCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Mixin.
        /// </summary>
        public static string TbSettingsEditMixin {
            get {
                return ResourceManager.GetString("TbSettingsEditMixin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        public static string TbSettingsException {
            get {
                return ResourceManager.GetString("TbSettingsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception. Do not use proxy server for addresses beginning with,Use semicolon (;).
        /// </summary>
        public static string TbSettingsExceptionTip {
            get {
                return ResourceManager.GetString("TbSettingsExceptionTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontFamily(Require restart).
        /// </summary>
        public static string TbSettingsFontFamily {
            get {
                return ResourceManager.GetString("TbSettingsFontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the font TTF file to the directory guiFonts, restart the settings.
        /// </summary>
        public static string TbSettingsFontFamilyTip {
            get {
                return ResourceManager.GetString("TbSettingsFontFamilyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontSize.
        /// </summary>
        public static string TbSettingsFontSize {
            get {
                return ResourceManager.GetString("TbSettingsFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Http Port.
        /// </summary>
        public static string TbSettingsHttpPort {
            get {
                return ResourceManager.GetString("TbSettingsHttpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable IPv6.
        /// </summary>
        public static string TbSettingsIpv6 {
            get {
                return ResourceManager.GetString("TbSettingsIpv6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language(restart).
        /// </summary>
        public static string TbSettingsLanguage {
            get {
                return ResourceManager.GetString("TbSettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Level.
        /// </summary>
        public static string TbSettingsLogLevel {
            get {
                return ResourceManager.GetString("TbSettingsLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed Port.
        /// </summary>
        public static string TbSettingsMixedPort {
            get {
                return ResourceManager.GetString("TbSettingsMixedPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Mixin configuration content.
        /// </summary>
        public static string TbSettingsMixin {
            get {
                return ResourceManager.GetString("TbSettingsMixin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pac listen port.
        /// </summary>
        public static string TbSettingsPacListenPort {
            get {
                return ResourceManager.GetString("TbSettingsPacListenPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After modifying the following parameters, click Save to take effect.
        /// </summary>
        public static string TbSettingsSaveTip {
            get {
                return ResourceManager.GetString("TbSettingsSaveTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Win10 UWP Loopback.
        /// </summary>
        public static string TbSettingsSetUWP {
            get {
                return ResourceManager.GetString("TbSettingsSetUWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socks Port.
        /// </summary>
        public static string TbSettingsSocksPort {
            get {
                return ResourceManager.GetString("TbSettingsSocksPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start on boot.
        /// </summary>
        public static string TbSettingsStartBoot {
            get {
                return ResourceManager.GetString("TbSettingsStartBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Statistics (Require restart).
        /// </summary>
        public static string TbSettingsStatistics {
            get {
                return ResourceManager.GetString("TbSettingsStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription conversion Url.
        /// </summary>
        public static string TbSettingsSubConvert {
            get {
                return ResourceManager.GetString("TbSettingsSubConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System proxy settings.
        /// </summary>
        public static string TbSettingsSystemproxy {
            get {
                return ResourceManager.GetString("TbSettingsSystemproxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Security Protocol TLS v1.3 (subscription/update).
        /// </summary>
        public static string TbSettingsTLS13 {
            get {
                return ResourceManager.GetString("TbSettingsTLS13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting.
        /// </summary>
        public static string TbSorting {
            get {
                return ResourceManager.GetString("TbSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain.
        /// </summary>
        public static string TbSortingChain {
            get {
                return ResourceManager.GetString("TbSortingChain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string TbSortingDefault {
            get {
                return ResourceManager.GetString("TbSortingDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        public static string TbSortingDelay {
            get {
                return ResourceManager.GetString("TbSortingDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Speed.
        /// </summary>
        public static string TbSortingDownSpeed {
            get {
                return ResourceManager.GetString("TbSortingDownSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Traffic.
        /// </summary>
        public static string TbSortingDownTraffic {
            get {
                return ResourceManager.GetString("TbSortingDownTraffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string TbSortingHost {
            get {
                return ResourceManager.GetString("TbSortingHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TbSortingName {
            get {
                return ResourceManager.GetString("TbSortingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string TbSortingNetwork {
            get {
                return ResourceManager.GetString("TbSortingNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string TbSortingTime {
            get {
                return ResourceManager.GetString("TbSortingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TbSortingType {
            get {
                return ResourceManager.GetString("TbSortingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Speed.
        /// </summary>
        public static string TbSortingUpSpeed {
            get {
                return ResourceManager.GetString("TbSortingUpSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Traffic.
        /// </summary>
        public static string TbSortingUpTraffic {
            get {
                return ResourceManager.GetString("TbSortingUpTraffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update subscription.
        /// </summary>
        public static string TbSubUpdateViaProxy {
            get {
                return ResourceManager.GetString("TbSubUpdateViaProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pac Mode.
        /// </summary>
        public static string TbSystemProxyPac {
            get {
                return ResourceManager.GetString("TbSystemProxyPac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string TbUrl {
            get {
                return ResourceManager.GetString("TbUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription url.
        /// </summary>
        public static string TbUrlAs {
            get {
                return ResourceManager.GetString("TbUrlAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Agent(optional).
        /// </summary>
        public static string TbUserAgent {
            get {
                return ResourceManager.GetString("TbUserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ping of current service: {0}.
        /// </summary>
        public static string TestMeOutput {
            get {
                return ResourceManager.GetString("TestMeOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To enable Tun mode, please use Clash.Meta Core first; or use Clash Premium Core.
        /// </summary>
        public static string TunModeCoreTip {
            get {
                return ResourceManager.GetString("TunModeCoreTip", resourceCulture);
            }
        }
    }
}
