//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace clashN.Resx
{
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResUI
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResUI()
        {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("clashN.Resx.ResUI", typeof(ResUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 All servers 的本地化字符串。
        /// </summary>
        internal static string AllGroupProfiles
        {
            get
            {
                return ResourceManager.GetString("AllGroupProfiles", resourceCulture);
            }
        }


        /// <summary>
        ///   查找类似 Batch export share URL to clipboard successfully 的本地化字符串。
        /// </summary>
        internal static string BatchExportSuccessfully
        {
            get
            {
                return ResourceManager.GetString("BatchExportSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Please check the server settings first 的本地化字符串。
        /// </summary>
        internal static string CheckProfileSettings
        {
            get
            {
                return ResourceManager.GetString("CheckProfileSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似  configuration format is incorrect 的本地化字符串。
        /// </summary>
        internal static string ConfigurationFormatIncorrect
        {
            get
            {
                return ResourceManager.GetString("ConfigurationFormatIncorrect", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Note that custom configuration relies entirely on your own configuration and does not work with all settings. If you want to use the system proxy, please modify the listening port manually. 的本地化字符串。
        /// </summary>
        internal static string CustomProfileTips
        {
            get
            {
                return ResourceManager.GetString("CustomProfileTips", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Downloading... 的本地化字符串。
        /// </summary>
        internal static string Downloading
        {
            get
            {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 DOWN 的本地化字符串。
        /// </summary>
        internal static string downloadSpeed
        {
            get
            {
                return ResourceManager.GetString("downloadSpeed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Whether to download? {0} 的本地化字符串。
        /// </summary>
        internal static string DownloadYesNo
        {
            get
            {
                return ResourceManager.GetString("DownloadYesNo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Failed to convert configuration file 的本地化字符串。
        /// </summary>
        internal static string FailedConversionConfiguration
        {
            get
            {
                return ResourceManager.GetString("FailedConversionConfiguration", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Failed to generate default configuration file 的本地化字符串。
        /// </summary>
        internal static string FailedGenDefaultConfiguration
        {
            get
            {
                return ResourceManager.GetString("FailedGenDefaultConfiguration", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似  Failed to get the default configuration 的本地化字符串。
        /// </summary>
        internal static string FailedGetDefaultConfiguration
        {
            get
            {
                return ResourceManager.GetString("FailedGetDefaultConfiguration", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Failed to import custom configuration server 的本地化字符串。
        /// </summary>
        internal static string FailedImportedCustomProfile
        {
            get
            {
                return ResourceManager.GetString("FailedImportedCustomProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Failed to read configuration file 的本地化字符串。
        /// </summary>
        internal static string FailedReadConfiguration
        {
            get
            {
                return ResourceManager.GetString("FailedReadConfiguration", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Please fill in the correct custom DNS 的本地化字符串。
        /// </summary>
        internal static string FillCorrectDNSText
        {
            get
            {
                return ResourceManager.GetString("FillCorrectDNSText", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Please fill in the correct format server port 的本地化字符串。
        /// </summary>
        internal static string FillCorrectProfilePort
        {
            get
            {
                return ResourceManager.GetString("FillCorrectProfilePort", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Please fill in the local listening port 的本地化字符串。
        /// </summary>
        internal static string FillLocalListeningPort
        {
            get
            {
                return ResourceManager.GetString("FillLocalListeningPort", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Please fill in the password 的本地化字符串。
        /// </summary>
        internal static string FillPassword
        {
            get
            {
                return ResourceManager.GetString("FillPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Please fill in the server address 的本地化字符串。
        /// </summary>
        internal static string FillProfileAddress
        {
            get
            {
                return ResourceManager.GetString("FillProfileAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Please browse to import server configuration 的本地化字符串。
        /// </summary>
        internal static string FillProfileAddressCustom
        {
            get
            {
                return ResourceManager.GetString("FillProfileAddressCustom", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Please fill in the user ID 的本地化字符串。
        /// </summary>
        internal static string FillUUID
        {
            get
            {
                return ResourceManager.GetString("FillUUID", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似  is not the correct client configuration file, please check 的本地化字符串。
        /// </summary>
        internal static string IncorrectClientConfiguration
        {
            get
            {
                return ResourceManager.GetString("IncorrectClientConfiguration", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似  is not the correct configuration, please check 的本地化字符串。
        /// </summary>
        internal static string Incorrectconfiguration
        {
            get
            {
                return ResourceManager.GetString("Incorrectconfiguration", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似  is not the correct server configuration file, please check 的本地化字符串。
        /// </summary>
        internal static string IncorrectProfileConfiguration
        {
            get
            {
                return ResourceManager.GetString("IncorrectProfileConfiguration", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Initial Configuration 的本地化字符串。
        /// </summary>
        internal static string InitialConfiguration
        {
            get
            {
                return ResourceManager.GetString("InitialConfiguration", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0} already up to date. 的本地化字符串。
        /// </summary>
        internal static string IsLatestCore
        {
            get
            {
                return ResourceManager.GetString("IsLatestCore", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0} already up to date. 的本地化字符串。
        /// </summary>
        internal static string IsLatestN
        {
            get
            {
                return ResourceManager.GetString("IsLatestN", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        internal static string LvAddress
        {
            get
            {
                return ResourceManager.GetString("LvAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Alias 的本地化字符串。
        /// </summary>
        internal static string LvAlias
        {
            get
            {
                return ResourceManager.GetString("LvAlias", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Count 的本地化字符串。
        /// </summary>
        internal static string LvCount
        {
            get
            {
                return ResourceManager.GetString("LvCount", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Custom Icon 的本地化字符串。
        /// </summary>
        internal static string LvCustomIcon
        {
            get
            {
                return ResourceManager.GetString("LvCustomIcon", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Security 的本地化字符串。
        /// </summary>
        internal static string LvEncryptionMethod
        {
            get
            {
                return ResourceManager.GetString("LvEncryptionMethod", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Port 的本地化字符串。
        /// </summary>
        internal static string LvPort
        {
            get
            {
                return ResourceManager.GetString("LvPort", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 remarks 的本地化字符串。
        /// </summary>
        internal static string LvRemarks
        {
            get
            {
                return ResourceManager.GetString("LvRemarks", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string LvServiceType
        {
            get
            {
                return ResourceManager.GetString("LvServiceType", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Subs 的本地化字符串。
        /// </summary>
        internal static string LvSubscription
        {
            get
            {
                return ResourceManager.GetString("LvSubscription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Test Results 的本地化字符串。
        /// </summary>
        internal static string LvTestResults
        {
            get
            {
                return ResourceManager.GetString("LvTestResults", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 TLS 的本地化字符串。
        /// </summary>
        internal static string LvTLS
        {
            get
            {
                return ResourceManager.GetString("LvTLS", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Today download traffic 的本地化字符串。
        /// </summary>
        internal static string LvTodayDownloadDataAmount
        {
            get
            {
                return ResourceManager.GetString("LvTodayDownloadDataAmount", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Today upload traffic 的本地化字符串。
        /// </summary>
        internal static string LvTodayUploadDataAmount
        {
            get
            {
                return ResourceManager.GetString("LvTodayUploadDataAmount", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Total download traffic 的本地化字符串。
        /// </summary>
        internal static string LvTotalDownloadDataAmount
        {
            get
            {
                return ResourceManager.GetString("LvTotalDownloadDataAmount", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Total upload traffic 的本地化字符串。
        /// </summary>
        internal static string LvTotalUploadDataAmount
        {
            get
            {
                return ResourceManager.GetString("LvTotalUploadDataAmount", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Transport 的本地化字符串。
        /// </summary>
        internal static string LvActivity
        {
            get
            {
                return ResourceManager.GetString("LvActivity", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Url 的本地化字符串。
        /// </summary>
        internal static string LvUrl
        {
            get
            {
                return ResourceManager.GetString("LvUrl", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 MediumFresh 的本地化字符串。
        /// </summary>
        internal static string MediumFresh
        {
            get
            {
                return ResourceManager.GetString("MediumFresh", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Clear original subscription content 的本地化字符串。
        /// </summary>
        internal static string MsgClearSubscription
        {
            get
            {
                return ResourceManager.GetString("MsgClearSubscription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Download GeoFile: {0} successfully 的本地化字符串。
        /// </summary>
        internal static string MsgDownloadGeoFileSuccessfully
        {
            get
            {
                return ResourceManager.GetString("MsgDownloadGeoFileSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Download Core successfully 的本地化字符串。
        /// </summary>
        internal static string MsgDownloadCoreSuccessfully
        {
            get
            {
                return ResourceManager.GetString("MsgDownloadCoreSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Failed to import subscription content 的本地化字符串。
        /// </summary>
        internal static string MsgFailedImportSubscription
        {
            get
            {
                return ResourceManager.GetString("MsgFailedImportSubscription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Get the subscription content successfully 的本地化字符串。
        /// </summary>
        internal static string MsgGetSubscriptionSuccessfully
        {
            get
            {
                return ResourceManager.GetString("MsgGetSubscriptionSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Informations (Filter : {0}) 的本地化字符串。
        /// </summary>
        internal static string MsgInformationTitle
        {
            get
            {
                return ResourceManager.GetString("MsgInformationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Please fill in the address (Url) 的本地化字符串。
        /// </summary>
        internal static string MsgNeedUrl
        {
            get
            {
                return ResourceManager.GetString("MsgNeedUrl", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 No valid subscriptions set 的本地化字符串。
        /// </summary>
        internal static string MsgNoValidSubscription
        {
            get
            {
                return ResourceManager.GetString("MsgNoValidSubscription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Resolve {0} successfully 的本地化字符串。
        /// </summary>
        internal static string MsgParsingSuccessfully
        {
            get
            {
                return ResourceManager.GetString("MsgParsingSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Start getting subscriptions 的本地化字符串。
        /// </summary>
        internal static string MsgStartGettingSubscriptions
        {
            get
            {
                return ResourceManager.GetString("MsgStartGettingSubscriptions", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Start updating {0}... 的本地化字符串。
        /// </summary>
        internal static string MsgStartUpdating
        {
            get
            {
                return ResourceManager.GetString("MsgStartUpdating", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Failed to get subscription content 的本地化字符串。
        /// </summary>
        internal static string MsgSubscriptionDecodingFailed
        {
            get
            {
                return ResourceManager.GetString("MsgSubscriptionDecodingFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 is unpacking... 的本地化字符串。
        /// </summary>
        internal static string MsgUnpacking
        {
            get
            {
                return ResourceManager.GetString("MsgUnpacking", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Update subscription end 的本地化字符串。
        /// </summary>
        internal static string MsgUpdateSubscriptionEnd
        {
            get
            {
                return ResourceManager.GetString("MsgUpdateSubscriptionEnd", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Update subscription starts 的本地化字符串。
        /// </summary>
        internal static string MsgUpdateSubscriptionStart
        {
            get
            {
                return ResourceManager.GetString("MsgUpdateSubscriptionStart", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Update Core successfully 的本地化字符串。
        /// </summary>
        internal static string MsgUpdateCoreCoreSuccessfully
        {
            get
            {
                return ResourceManager.GetString("MsgUpdateCoreCoreSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Update Core successfully! Restarting service... 的本地化字符串。
        /// </summary>
        internal static string MsgUpdateCoreCoreSuccessfullyMore
        {
            get
            {
                return ResourceManager.GetString("MsgUpdateCoreCoreSuccessfullyMore", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似  This feature relies on the Http global proxy, please set it correctly first. 的本地化字符串。
        /// </summary>
        internal static string NeedHttpGlobalProxy
        {
            get
            {
                return ResourceManager.GetString("NeedHttpGlobalProxy", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Core not found, please download: {0} 的本地化字符串。
        /// </summary>
        internal static string NotFoundCore
        {
            get
            {
                return ResourceManager.GetString("NotFoundCore", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Scan completed, no valid QR code found 的本地化字符串。
        /// </summary>
        internal static string NoValidQRcodeFound
        {
            get
            {
                return ResourceManager.GetString("NoValidQRcodeFound", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似  operation failed, please check retry 的本地化字符串。
        /// </summary>
        internal static string OperationFailed
        {
            get
            {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Operation success 的本地化字符串。
        /// </summary>
        internal static string OperationSuccess
        {
            get
            {
                return ResourceManager.GetString("OperationSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Please Fill Remarks 的本地化字符串。
        /// </summary>
        internal static string PleaseFillRemarks
        {
            get
            {
                return ResourceManager.GetString("PleaseFillRemarks", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Please select the encryption method 的本地化字符串。
        /// </summary>
        internal static string PleaseSelectEncryption
        {
            get
            {
                return ResourceManager.GetString("PleaseSelectEncryption", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Please select an agreement 的本地化字符串。
        /// </summary>
        internal static string PleaseSelectProtocol
        {
            get
            {
                return ResourceManager.GetString("PleaseSelectProtocol", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Please select rules 的本地化字符串。
        /// </summary>
        internal static string PleaseSelectRules
        {
            get
            {
                return ResourceManager.GetString("PleaseSelectRules", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Please select the server first 的本地化字符串。
        /// </summary>
        internal static string PleaseSelectProfile
        {
            get
            {
                return ResourceManager.GetString("PleaseSelectProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 QuickFresh 的本地化字符串。
        /// </summary>
        internal static string QuickFresh
        {
            get
            {
                return ResourceManager.GetString("QuickFresh", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Global hotkey {0} registered failed, reason {1} 的本地化字符串。
        /// </summary>
        internal static string RegisterGlobalHotkeyFailed
        {
            get
            {
                return ResourceManager.GetString("RegisterGlobalHotkeyFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Global hotkey {0} registered successfully 的本地化字符串。
        /// </summary>
        internal static string RegisterGlobalHotkeySuccessfully
        {
            get
            {
                return ResourceManager.GetString("RegisterGlobalHotkeySuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Profiles deduplication completed. Old: {0}, New: {1}. 的本地化字符串。
        /// </summary>
        internal static string RemoveDuplicateProfileResult
        {
            get
            {
                return ResourceManager.GetString("RemoveDuplicateProfileResult", resourceCulture);
            }
        }


        /// <summary>
        ///   查找类似 Are you sure to remove the server? 的本地化字符串。
        /// </summary>
        internal static string RemoveProfile
        {
            get
            {
                return ResourceManager.GetString("RemoveProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 SlowFresh 的本地化字符串。
        /// </summary>
        internal static string SlowFresh
        {
            get
            {
                return ResourceManager.GetString("SlowFresh", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Note: After this function relies on the Http global proxy test, please manually adjust the Http global proxy and active node! 的本地化字符串。
        /// </summary>
        internal static string SpeedProfileTips
        {
            get
            {
                return ResourceManager.GetString("SpeedProfileTips", resourceCulture);
            }
        }


        /// <summary>
        ///   查找类似 Start service ({0})... 的本地化字符串。
        /// </summary>
        internal static string StartService
        {
            get
            {
                return ResourceManager.GetString("StartService", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Successful configuration
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string SuccessfulConfiguration
        {
            get
            {
                return ResourceManager.GetString("SuccessfulConfiguration", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Successfully imported custom configuration server 的本地化字符串。
        /// </summary>
        internal static string SuccessfullyImportedCustomProfile
        {
            get
            {
                return ResourceManager.GetString("SuccessfullyImportedCustomProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0} servers have been imported from clipboard. 的本地化字符串。
        /// </summary>
        internal static string SuccessfullyImportedProfileViaClipboard
        {
            get
            {
                return ResourceManager.GetString("SuccessfullyImportedProfileViaClipboard", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Scan import URL successfully 的本地化字符串。
        /// </summary>
        internal static string SuccessfullyImportedProfileViaScan
        {
            get
            {
                return ResourceManager.GetString("SuccessfullyImportedProfileViaScan", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The ping of current service: {0} 的本地化字符串。
        /// </summary>
        internal static string TestMeOutput
        {
            get
            {
                return ResourceManager.GetString("TestMeOutput", resourceCulture);
            }
        }
        internal static string RunAsAdmin
        {
            get
            {
                return ResourceManager.GetString("RunAsAdmin", resourceCulture);
            }
        }
        internal static string NotRunAsAdmin
        {
            get
            {
                return ResourceManager.GetString("NotRunAsAdmin", resourceCulture);
            }
        }
        internal static string EnableTunModeFailed
        {
            get
            {
                return ResourceManager.GetString("EnableTunModeFailed", resourceCulture);
            }
        }
        internal static string LvEnableTun
        {
            get
            {
                return ResourceManager.GetString("LvEnableTun", resourceCulture);
            }
        }
        internal static string LvEnableUpdateSub
        {
            get
            {
                return ResourceManager.GetString("LvEnableUpdateSub", resourceCulture);
            }
        }
    }
}
